### ISSUE TITLE
Slow zsh startup

### ISSUE THREAD

**Issue by Ralith** [rycee/home-manager#108]
On current master, atop nixos 17.09: `zsh -i -c exit` => `1.42s user 0.10s system 99% cpu 1.530 total`

I have `programs.zsh.enable = true;` in my system config *and* in home.nix, and have `nix-zsh-completions` and `zsh-navigation-tools` installed globally. I have no custom zsh config in effect.

**Comment by uvNikita** [comment]
Thank you for creating the issue!

I can confirm the slowdown if I have `programs.zsh.enable = true` in both system and home configurations. Interesting that enabling `progmas.zsh.oh-my-zsh` in home configuration fixes the issue. I will try to look into it more.

**Comment by uvNikita** [comment]
The reason for the slowdown seems to be that `compinit` is called twice in this case: once in (system zshrc)[https://github.com/NixOS/nixpkgs/blob/05c9a95d0e1c52dde3c2b10a31d3fe9ead5ed560/nixos/modules/programs/zsh/zsh.nix#L166] and once in (home zshrc)[https://github.com/rycee/home-manager/blob/268d027770a853ca21ff695755ab05c0349817ef/modules/programs/zsh.nix#L257]. To fix this, you can disable completions in any of two configurations, depending if you wish completions to be enabled globally, or per-user. Not sure if we can do more on our side.

**Comment by LnL7** [comment]
@uvNikita if your `fpath` changes between calling compinit it'll cause the caches to invalidate every time you start a new shell.

**Comment by uvNikita** [comment]
@LnL7 Yes, indeed you seem to be right, thank you for the insight! I pushed a commit that turns fpath into a set (following the recommendation from the example [.zshenv](http://zsh.sourceforge.net/Contrib/startup/users/debbiep/dot.zshenv) on zsh website). Due to this, fpath value remains the same between compinit calls when zsh is enabled in both configurations. This fixed issue on my machine. Note, that if you will add plugins into your home configuration (through `programs.zsh.plugins` option), fpath will be changed again and the issue might reappear. It that case I would disable systemwide completions.

@Ralith Let me know if you will still experience the slowdown.

**Comment by Ralith** [comment]
`zsh -i -c exit  0.09s user 0.02s system 98% cpu 0.115 total`

Seems like this is fixed, thanks! Still not instant but I have no particular reason to believe it was ever faster than that.

**Comment by Fxzzi** [comment]
thanks for the fix, seems to have magically dropped my shell init times dramatically :)

however, without defining zsh in the os configuration, how can you se the users shell to zsh? is

```nix
  users.users.<user> = {
    shell = pkgs.zsh; # Set shell to zsh
    ignoreShellProgramCheck = true;
```

fine to do in this case?

**Comment by michael-nhat** [comment]
I meet slowness problem of zsh when define in both nixos and HM config, it took 2-5 second to startup shell. I searched and tried so much. Only final config line help me solve long startup time of zsh: `programs.zsh.enableGlobalCompInit = false;` in nixos config. Hope that help anyone.

**Comment by miksa234** [comment]
I am symlinking my zsh configuration  via home-manager (still migrating to nixos).  However the global zshrc file is making my zsh startup super slow because of a double compinit run and breaking my completions (some completions work some don't). 

Managed to solve this by still having
  
`programs.zsh.enable = true`

and not sourcing the global zshrc  by setting

``` 
environment.variables = {
  __ETC_ZSHRC_SOURCED = "1";
};
```

This keeps the `/etc/zshenv` file sourced, because it needs to update the `fpath`  of nix packages.
I am then running `compinit`  or `compinit -C` in my `.zshrc`.
